export const demoStartups = [
  {
    id: "demo-1",
    name: "Releaf",
    tagline: "A second life for every leaf.",
    category: "Sustainability",
    stage: "Prototype",
    problem:
      "Agricultural waste is often burned, adding to air pollution while useful natural materials go unused.",
    solution:
      "We turn agricultural residue into compostable packaging that replaces single-use plastic.",
    productDescription:
      "Plant-based protective packaging made from locally sourced agricultural waste.",
    targetUsers: "Local retailers, D2C brands and small manufacturers.",
    businessModel: "B2B packaging supply.",
    founderName: "Ananya & team",
    department: "Mechanical Engineering",
    productStatus: "Working prototype",
    hiring: true,
    requiredRoles: ["Designers", "Marketing"],
    requiredSkills: "Product design, materials research, storytelling",
    opportunity: "Help us make sustainable packaging accessible.",
    stall: "01",
    theme: "mint",
    symbol: "leaf",
    tags: ["Circular economy", "Eco packaging"],
    members: [
      {
        name: "Ananya Rao",
        role: "Co-founder",
        skills: "Materials engineering",
      },
      { name: "Rohan Kumar", role: "Product lead", skills: "Product design" },
    ],
  },
  {
    id: "demo-2",
    name: "NeuroNote",
    tagline: "Less note-taking. More understanding.",
    category: "AI / ML",
    stage: "MVP",
    problem:
      "Students spend more time copying lectures than understanding concepts.",
    solution:
      "An AI study companion that transforms lectures into connected notes and tailored revision.",
    productDescription:
      "A learning workspace for lecture summaries, concept maps and active recall.",
    targetUsers: "College students and independent learners.",
    businessModel: "Freemium subscription.",
    founderName: "Arjun & team",
    department: "Computer Science",
    productStatus: "Live product",
    hiring: true,
    requiredRoles: ["Developers"],
    requiredSkills: "React, machine learning, Python",
    opportunity: "Build the next version of our AI study workspace.",
    stall: "02",
    theme: "violet",
    symbol: "brain",
    tags: ["Generative AI", "Student-built"],
    members: [
      { name: "Arjun Reddy", role: "Founder", skills: "Machine learning" },
    ],
  },
  {
    id: "demo-3",
    name: "PulsePoint",
    tagline: "Care that’s always a beat ahead.",
    category: "HealthTech",
    stage: "Prototype",
    problem:
      "Regular health monitoring can be expensive and difficult to access.",
    solution:
      "An affordable connected wearable that makes everyday health trends easier to understand.",
    productDescription:
      "A wearable sensor prototype paired with a simple monitoring interface.",
    targetUsers: "People seeking accessible everyday wellness monitoring.",
    businessModel: "Device sales with a companion application.",
    founderName: "Sneha & team",
    department: "Electronics & Communication",
    productStatus: "Working prototype",
    hiring: true,
    requiredRoles: ["Developers", "Designers"],
    requiredSkills: "Embedded systems, UX design",
    opportunity: "Help design and prototype accessible wellness technology.",
    stall: "03",
    theme: "sky",
    symbol: "pulse",
    tags: ["Wearables", "Connected care"],
    members: [
      { name: "Sneha Patel", role: "Co-founder", skills: "Embedded systems" },
    ],
  },
  {
    id: "demo-4",
    name: "BuildGrid",
    tagline: "Smarter sites. Stronger foundations.",
    category: "ConstructionTech",
    stage: "Early Users",
    problem:
      "Small construction projects rely on fragmented spreadsheets and messages.",
    solution:
      "A shared project workspace for site progress, materials and crew coordination.",
    productDescription: "A mobile-first construction operations dashboard.",
    targetUsers: "Independent contractors and small construction teams.",
    businessModel: "Monthly subscription per active project.",
    founderName: "Karthik & team",
    department: "Civil Engineering",
    productStatus: "Live product",
    hiring: false,
    requiredRoles: [],
    stall: "04",
    theme: "amber",
    symbol: "grid",
    tags: ["Site management", "B2B"],
    members: [
      { name: "Karthik Nair", role: "Founder", skills: "Civil engineering" },
    ],
  },
  {
    id: "demo-5",
    name: "Pocketwise",
    tagline: "Small habits. Bigger possibilities.",
    category: "FinTech",
    stage: "MVP",
    problem:
      "Students lack a simple way to understand daily spending and build saving habits.",
    solution:
      "A friendly spending journal with personal budgets and savings goals.",
    productDescription:
      "A personal budgeting application designed for campus life.",
    targetUsers: "College students.",
    businessModel: "Freemium subscription.",
    founderName: "Meghana & team",
    department: "Information Technology",
    productStatus: "Live product",
    hiring: true,
    requiredRoles: ["Marketing"],
    requiredSkills: "Community building, content",
    opportunity: "Build our student community.",
    stall: "05",
    theme: "peri",
    symbol: "wallet",
    tags: ["Personal finance", "Student life"],
    members: [
      { name: "Meghana Rao", role: "Founder", skills: "Product management" },
    ],
  },
  {
    id: "demo-6",
    name: "SkillSwap",
    tagline: "Your skill. Someone’s next step.",
    category: "EdTech",
    stage: "Idea",
    problem:
      "Students have useful skills but few opportunities to exchange them with peers.",
    solution:
      "A campus network for exchanging skills through peer-led sessions.",
    productDescription: "A peer-to-peer learning network concept.",
    targetUsers: "Students interested in collaborative learning.",
    businessModel: "Campus partnerships.",
    founderName: "Aditya & team",
    department: "Computer Science",
    productStatus: "Concept only",
    hiring: true,
    requiredRoles: ["Co-founders", "Developers"],
    requiredSkills: "Web development, community management",
    opportunity: "Shape a learning community from day one.",
    stall: "06",
    theme: "coral",
    symbol: "spark",
    tags: ["Peer learning", "Community"],
    members: [
      { name: "Aditya Shah", role: "Founder", skills: "Community building" },
    ],
  },
];
